# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Expose the default MongoDB port (27017)
EXPOSE 27017

# Set the default command to run when the container starts
CMD ["mongod"]
